/*
 * GpioConfig.c
 *
 *  Created on: 3 Kas 2022
 *      Author: mehme
 */

/*****************THE PROCEDURE OF GPIO CONFIGURATION ARE GIVEN FOLLOWING****************/
/*
 * 1-ENABLE CLOCK BUS OF GPIO A AND GPIO D.
 * 2-CONFIGURE MODE OF GPIO A AND GPIO D.
 * 3-CONFIGURE OUTPUT TYPE OF GPIO A AND GPIO D.
 * 4-CONFIGURE OUTPUT SPEED OF GPIO A AND GPIO D.
 * 5-CONFIGURE PULL DOWN OR PULL UP RESISTOR OF GPIO A AND GPIO D.
 * 6-SET SP1 FOR ALTERNATE FUNCTION OF GPIO A.
 */



#include "GpioConfig.h"


void Gpio_Config(void){

	RCC->AHB1ENR |=(1<<0);  //GPIOA CLOCK BUS ENABLE
	RCC->AHB1ENR |=(1<<3);	//GPIOD CLOCK BUS ENABLE

	GPIOA->MODER |=(2<<10); //5,6,7. Pins of PortA selected as alternative function
	GPIOA->MODER |=(2<<12); //PA5-->>SCL PA6-->>MISO PA7->>MOSI
	GPIOA->MODER |=(2<<14);
	GPIOA->MODER |=(1<<8);  //4. PIN OF PORT A SEECTED AS OUTPUT MODE

	GPIOD->MODER |=(1<<24)|(1<<26)|(1<<28)|(1<<30);//12,13,14,15 PINS of PORT D selected as output mode
												   //SELECTED as OUTPUT MODE


	GPIOD->OTYPER &=~(1<<12);//GPIO D OUTPUT MODE IS SELECTED PUSH-PULL
	GPIOD->OTYPER &=~(1<<13);
	GPIOD->OTYPER &=~(1<<14);
	GPIOD->OTYPER &=~(1<<15);

	GPIOA->OTYPER &=~(1<<4);//GPIO A OUTPUT MODE IS SELECTED PUSH-PULL
	GPIOA->OTYPER &=~(1<<5);
	GPIOA->OTYPER &=~(1<<6);
	GPIOA->OTYPER &=~(1<<7);

	GPIOD->OSPEEDR |=(3<<24) | (3<<26)| (3<<28)| (3<<30);
	GPIOA->OSPEEDR |=(3<<8)|(3<<10)|(3<<12)|(3<<14);

	GPIOD->PUPDR |=(2<8);//4.PIN OF GPIOA SET PULL-DOWN.

	// PIN5,PIN6,PIN7 of PORT A IS SELECTED ALTERNATE FUNCTION FOR SPI1
	GPIOA->AFR[0] |=(5<<20);
	GPIOA->AFR[0] |=(5<<24);
	GPIOA->AFR[0] |=(5<<28);


}
